baseurl = "https://tiyalla.github.io" # Hostname (and path) to the root.

title = "Tonye Iyalla" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Tonye Iyalla" # Author's name.
    info = "Master's Student and Software Engineer" # Author's job title or info.
    description = "Tonye Iyalla's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.png" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content
    fixedbarContent = "Want to connect with me?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! →" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/tiyalla/"

[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/tonyeiyalla92/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url  = "about"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "posts"
[[menu.main]]
    name = "Projects"
    weight = 3
    url  = "projects"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "contact"